source :rubygems
gem 'sinatra'
gem 'shotgun'
gem 'rspec', '>=2.10.0'
gem 'clockwork'
gem 'gcalapi'
gem 'mechanize'
gem 'parallel_runner', '>=0.0.3'
gem 'active_support'
gem 'i18n'
gem 'twitter'
gem 'httpclient'
gem 'log4ever'
